### ISSUE TITLE
NSKeyedArchiver Support?

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm#11]
@asmagill - I've been playing around with `hs._asm.preferences`, and it's awesome. Thank you!

Any chance of adding `NSKeyedArchiver` support?

**Comment by asmagill** [comment]
This has been superseded by a cfprefernces approach and keyed archiver support is a planned feature for the module when it's closer to completion; closing this.  Feel free to reopen if you disagree or think it should be handled separately.
