### ISSUE TITLE
Errors in Console when using axh.lua

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm#2]
I'm getting the following errors in the console, when trying to run the code within **axh.lua**:

> *** ERROR: ...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: module 'inspect' not found:
> 	no field package.preload['inspect']
> 	no file '/Users/latenitechris/.hammerspoon/inspect.lua'
> 	no file '/Users/latenitechris/.hammerspoon/inspect/init.lua'
> 	no file '/usr/local/share/lua/5.3/inspect.lua'
> 	no file '/usr/local/share/lua/5.3/inspect/init.lua'
> 	no file '/usr/local/lib/lua/5.3/inspect.lua'
> 	no file '/usr/local/lib/lua/5.3/inspect/init.lua'
> 	no file './inspect.lua'
> 	no file './inspect/init.lua'
> 	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/inspect.lua'
> 	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/inspect/init.lua'
> 	no file '/Users/latenitechris/.hammerspoon/inspect.so'
> 	no file '/usr/local/lib/lua/5.3/inspect.so'
> 	no file '/usr/local/lib/lua/5.3/loadall.so'
> 	no file './inspect.so'
> 	no file '/Applications/Hammerspoon.app/Contents/Resources/extensions/inspect.so'
> stack traceback:
> 	[C]: in function 'rawrequire'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:449: in function 'require'
> 	/Users/latenitechris/.hammerspoon/init.lua:750: in main chunk
> 	[C]: in function 'xpcall'
> 	...app/Contents/Resources/extensions/hs/_coresetup/init.lua:481: in function 'hs._coresetup.setup'
> 	(...tail calls...)
 
Thoughts?

**Comment by asmagill** [comment]
Sorry about that -- I left out "hs." in the require statement... It should be corrected now.

**Comment by latenitefilms** [comment]
Thanks! Sorry... dumb question, but how do I actually use this? How can I trigger it off a shortcut key?

**Comment by asmagill** [comment]
This function is meant for informational purposes... it's not something you'd want to run very often, but may help in determining the best way to craft specific queries, once that support is added... I'll try and add an example of using it later tonight when I am back on my home computer because I suspect I will want to see how Final Cut Pro is organizing its accessibility objects (beyond what you've already shared) at some point -- but not necessarily yet :-)
