### ISSUE TITLE
Touch Bar - Error Message Always Displayed

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm#8]
@asmagill - I haven't had a chance to test first hand as my laptop is running 10.12.1, but I'm told that if you don't have macOS 10.12.1 build 16B2657 or greater, as soon as you "require" **hs._asm.touchbar**, it will display the built-in error message. I believe the intention was to have the error message off by default (hence the reason for **touchbar.supported()**)?

**Comment by asmagill** [comment]
I've been going back and forth about whether it should prompt immediately if you try to load the module as a way to minimize questions along the lines of "why doesn't it work for me?" when we move it into core...

I'll take this as a vote against?  What about prompting if you attempt to run the `new` function when it's not supported with the current os?  That way the module would load, but it would prompt the user if you actually tried to *create* a touchbar on an unsupported machine? Currently it will just return nil in that situation.

For now, if you want to suppress it, remove the "true" argument in line 12 of `hs/_asm/touchbar/init.lua`.

**Comment by randomeizer** [comment]
Personally, I would much rather it happened in the `new` function, and threw an error. Right now, if I'm on El Capitan, I get an ugly dialog box every time the 'require' happens, and there's no way to avoid it in code.

**Comment by asmagill** [comment]
The latest version no longer prompts if you do not have the necessary support for the Touch Bar.  If your code goes ahead and calls the `new` function anyways, that *will* prompt, so... make sure you check `supported` first and then provide your own fallback/message to the user as appropriate.

For the record, the difference between v0.6 and v0.6.1 is primarily in documentation and won't affect your current use of the module.

**Comment by randomeizer** [comment]
Perfect, thanks.

**Comment by latenitefilms** [comment]
Legend, thanks heaps @asmagill! Very much appreciated!
