### ISSUE TITLE
Apple Script Widget

### ISSUE THREAD

**Issue by latenitefilms** [asmagill/hammerspoon_asm#9]
Something like this would be a really cool addition to your Touch Bar extension:

http://docs.bettertouchtool.net/docs/touch_bar_widgets.html

**Comment by asmagill** [comment]
Probably a bit beyond what I've got so far... while I still hope to one day add a module for creating a true Hammerspoon touch bar, I'm still not aware of an official way to inject into the touchbar of other applications or in general.  That said, I haven't looked into it in a while, so perhaps Apple has added some examples or APIs that I'm not aware of yet.. there have been a couple of updates.

But something to keep in mind.

**Comment by latenitefilms** [comment]
A trick way could be to just implement a Hammerspoon Touch Bar, then if you want to access it via another app, you could hold down a shortcut key that temporarily brings Hammerspoon to front - thus activating the Hammerspoon Touch Bar. Release the shortcut, and the focus goes back to the original app.

**Comment by asmagill** [comment]
I think this is slowly getting implemented with `hs._asm.undocumented.touchbar`. If you disagree, feel free to re-open.

**Comment by latenitefilms** [comment]
Yes, what you've already done is truly awesome. THANK YOU!
